### ISSUE TITLE
https://denopkg.com/ is offline

### ISSUE THREAD

**Issue by lucis** [egoist-labs/denopkg.com#35]
My Fresh app build fails because one subdependency is being fetched from `denopkg.com`

![image](https://user-images.githubusercontent.com/18706156/210007418-6dc169b4-a542-4eaa-8876-37a6351ca84c.png)

![image](https://user-images.githubusercontent.com/18706156/210007433-9f2eaff0-1134-4f35-8ca2-53b260c54609.png)

**Comment by sblatz** [comment]
Also seeing this, an import I used to use is now failing because of this.

**Comment by lucis** [comment]
It's back online

![image](https://user-images.githubusercontent.com/18706156/210094870-791a9f89-1e9e-4861-b7e7-425714ba6b30.png)

**Comment by egoist** [comment]
sorry i transferred the domain and forgot to transfer dns records.
